/**
 * `cortexos init` — Project setup wizard
 * Creates .cortexos.yaml config and .cortexos/ directory in the project.
 */

import { Command } from 'commander';
import { resolve, join } from 'path';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { VERSION } from '../../version.js';

export function createInitCommand(): Command {
  const cmd = new Command('init');

  cmd
    .description('Initialize CortexOS in the current project')
    .option('-d, --dir <directory>', 'Project directory', '.')
    .option('--force', 'Overwrite existing configuration')
    .option('--minimal', 'Create minimal configuration')
    .action(async (options: InitOptions) => {
      await executeInit(options);
    });

  return cmd;
}

interface InitOptions {
  dir: string;
  force?: boolean;
  minimal?: boolean;
}

async function executeInit(options: InitOptions): Promise<void> {
  const projectDir = resolve(options.dir);
  const configPath = join(projectDir, '.cortexos.yaml');
  const dataDir = join(projectDir, '.cortexos');

  console.log();
  console.log(`🧠 CortexOS v${VERSION} — Project Initialization`);
  console.log();

  // Check if already initialized
  if (existsSync(configPath) && !options.force) {
    console.log(`⚠️  CortexOS already initialized in this project.`);
    console.log(`   Use --force to overwrite existing configuration.`);
    console.log();
    return;
  }

  // Create data directory
  if (!existsSync(dataDir)) {
    mkdirSync(dataDir, { recursive: true });
    console.log(`📁 Created .cortexos/ directory`);
  }

  // Create gitignore for .cortexos directory
  const gitignorePath = join(dataDir, '.gitignore');
  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, [
      '# CortexOS local data',
      'memory/',
      'worktrees/',
      'logs/',
      '*.db',
      '*.sqlite',
    ].join('\n') + '\n');
    console.log(`📝 Created .cortexos/.gitignore`);
  }

  // Create memory directory
  const memoryDir = join(dataDir, 'memory');
  if (!existsSync(memoryDir)) {
    mkdirSync(memoryDir, { recursive: true });
  }

  // Create config file
  const configContent = options.minimal
    ? generateMinimalConfig()
    : generateFullConfig();

  writeFileSync(configPath, configContent);
  console.log(`⚙️  Created .cortexos.yaml`);

  // Check for .gitignore and suggest adding .cortexos/
  const projectGitignore = join(projectDir, '.gitignore');
  if (existsSync(projectGitignore)) {
    const content = require('fs').readFileSync(projectGitignore, 'utf-8');
    if (!content.includes('.cortexos')) {
      console.log();
      console.log(`💡 Tip: Add '.cortexos/' to your .gitignore to exclude local data.`);
    }
  }

  console.log();
  console.log(`✅ CortexOS initialized! Run \`cortexos "your task"\` to get started.`);
  console.log();
}

function generateMinimalConfig(): string {
  return `# CortexOS Project Configuration
# See: https://github.com/cortexos/cortexos

# Default provider (auto-detected from environment variables)
# provider: anthropic

# Memory system
memory:
  enabled: true
`;
}

function generateFullConfig(): string {
  return `# CortexOS Project Configuration
# Generated by cortexos init v${VERSION}

# Default LLM provider (auto-detected from API keys)
# Options: anthropic, openai, google, ollama
# provider: anthropic

# Default model (per provider)
# model: claude-3-5-sonnet-20241022

# Budget limits
budget:
  maxCostPerRun: 5.00    # Maximum cost per execution ($)
  maxCostPerDay: 50.00   # Maximum daily cost ($)
  warningThreshold: 0.8  # Warn at 80% of budget

# Memory system
memory:
  enabled: true
  # decay: true           # Enable Ebbinghaus forgetting curves
  # decayHalfLife: 30     # Days before memory importance halves

# Agent configuration
agents:
  maxParallel: 4          # Maximum parallel agents
  maxIterations: 20       # Maximum tool-use iterations per agent
  # timeout: 300          # Timeout per agent (seconds)

# Quality gates
quality:
  enabled: true
  gates:
    - syntax              # Basic syntax validation
    - lint                # Run linter if available
    # - typeCheck          # TypeScript type checking
    # - test              # Run test suite
    # - review            # LLM-based code review

# Project-specific instructions
# instructions: |
#   This is an Express.js API with PostgreSQL.
#   Follow RESTful conventions.
#   All endpoints need authentication middleware.

# File patterns to ignore
ignore:
  - node_modules
  - dist
  - build
  - .git
  - coverage
`;
}
